# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel
from ...utils.unions import parse_open_union
from .deepresearchagentconfig import (
    DeepResearchAgentConfig,
    DeepResearchAgentConfigParam,
)
from .dynamicagentconfig import DynamicAgentConfig, DynamicAgentConfigParam
from functools import partial
from pydantic import ConfigDict
from pydantic.functional_validators import BeforeValidator
from typing import Any, Literal, Union
from typing_extensions import Annotated, TypeAliasType


AgentConfigParam = TypeAliasType(
    "AgentConfigParam", Union[DynamicAgentConfigParam, DeepResearchAgentConfigParam]
)
r"""Agent configuration variants discriminated by `type`."""


class UnknownAgentConfig(BaseModel):
    r"""A AgentConfig variant the SDK doesn't recognize. Preserves the raw payload."""

    type: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)


_AGENT_CONFIG_VARIANTS: dict[str, Any] = {
    "dynamic": DynamicAgentConfig,
    "deep-research": DeepResearchAgentConfig,
}


AgentConfig = Annotated[
    Union[DynamicAgentConfig, DeepResearchAgentConfig, UnknownAgentConfig],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="type",
            variants=_AGENT_CONFIG_VARIANTS,
            unknown_cls=UnknownAgentConfig,
            union_name="AgentConfig",
        )
    ),
]
r"""Agent configuration variants discriminated by `type`."""
