# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


TransformParam = TypeAliasType(
    "TransformParam", Union[List[Dict[str, str]], Dict[str, str]]
)
r"""Headers to inject on all outbound requests matching this domain. Accepts a single dict or a list of dicts. The egress proxy injects these automatically."""


Transform = TypeAliasType("Transform", Union[List[Dict[str, str]], Dict[str, str]])
r"""Headers to inject on all outbound requests matching this domain. Accepts a single dict or a list of dicts. The egress proxy injects these automatically."""


class AllowlistEntryParam(TypedDict):
    r"""A network egress rule that controls which external domains the
    environment is allowed to reach.  Each rule identifies a target domain
    and, optionally, a set of HTTP headers to inject into every matching
    outbound request.
    """

    domain: str
    r"""The domain pattern to match for this rule.
    Use an exact hostname (e.g., `github.com`), a wildcard prefix
    (e.g., `*.googleapis.com`), or `*` to match all domains.
    """
    transform: NotRequired[TransformParam]
    r"""Headers to inject on all outbound requests matching this domain. Accepts a single dict or a list of dicts. The egress proxy injects these automatically."""


class AllowlistEntry(BaseModel):
    r"""A network egress rule that controls which external domains the
    environment is allowed to reach.  Each rule identifies a target domain
    and, optionally, a set of HTTP headers to inject into every matching
    outbound request.
    """

    domain: str
    r"""The domain pattern to match for this rule.
    Use an exact hostname (e.g., `github.com`), a wildcard prefix
    (e.g., `*.googleapis.com`), or `*` to match all domains.
    """

    transform: Optional[Transform] = None
    r"""Headers to inject on all outbound requests matching this domain. Accepts a single dict or a list of dicts. The egress proxy injects these automatically."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["transform"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
