# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from ...utils import validate_const
from .filecontent import FileContent, FileContentParam
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


Mode = Union[
    Literal[
        "scan",
        "verify",
    ],
    UnrecognizedStr,
]
r"""The mode of the find session."""


class FindRequestParam(TypedDict):
    r"""Parameters for finding vulnerabilities."""

    source_files: NotRequired[List[FileContentParam]]
    r"""A list of source files to provide as context for the scan."""
    finding_id: NotRequired[str]
    r"""The identifier of a specific finding to verify. This is primarily used in
    VERIFY mode to focus the agent's execution-based validation on a single
    vulnerability.
    """
    description: NotRequired[str]
    r"""Additional context or custom instructions provided by the user to guide
    the vulnerability analysis.
    """
    mode: NotRequired[Mode]
    r"""The mode of the find session."""


class FindRequest(BaseModel):
    r"""Parameters for finding vulnerabilities."""

    source_files: Optional[List[FileContent]] = None
    r"""A list of source files to provide as context for the scan."""

    finding_id: Optional[str] = None
    r"""The identifier of a specific finding to verify. This is primarily used in
    VERIFY mode to focus the agent's execution-based validation on a single
    vulnerability.
    """

    description: Optional[str] = None
    r"""Additional context or custom instructions provided by the user to guide
    the vulnerability analysis.
    """

    mode: Optional[Mode] = None
    r"""The mode of the find session."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["source_files", "finding_id", "description", "mode"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class FixRequestParam(TypedDict):
    r"""Parameters for fixing vulnerabilities."""

    source_files: NotRequired[List[FileContentParam]]
    r"""A list of source files providing context for the remediation. These files
    are typically the ones containing the identified vulnerability.
    """
    finding_id: NotRequired[str]
    r"""The identifier of the specific security finding to be remediated. This ID
    maps to a previously discovered vulnerability.
    """
    description: NotRequired[str]
    r"""Additional context or custom instructions provided by the user to guide
    the patch generation process.
    """


class FixRequest(BaseModel):
    r"""Parameters for fixing vulnerabilities."""

    source_files: Optional[List[FileContent]] = None
    r"""A list of source files providing context for the remediation. These files
    are typically the ones containing the identified vulnerability.
    """

    finding_id: Optional[str] = None
    r"""The identifier of the specific security finding to be remediated. This ID
    maps to a previously discovered vulnerability.
    """

    description: Optional[str] = None
    r"""Additional context or custom instructions provided by the user to guide
    the patch generation process.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["source_files", "finding_id", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SessionConfigParam(TypedDict):
    r"""Optional session-specific configurations to override default agent
    behavior.
    """

    max_rounds: NotRequired[int]
    r"""The maximum number of interaction rounds the agent is allowed to perform
    before reaching a timeout.
    """


class SessionConfig(BaseModel):
    r"""Optional session-specific configurations to override default agent
    behavior.
    """

    max_rounds: Optional[int] = None
    r"""The maximum number of interaction rounds the agent is allowed to perform
    before reaching a timeout.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["max_rounds"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CodeMenderAgentConfigParam(TypedDict):
    r"""Configuration for the CodeMender agent."""

    type: Literal["code-mender"]
    find_request: NotRequired[FindRequestParam]
    r"""Parameters for finding vulnerabilities."""
    fix_request: NotRequired[FixRequestParam]
    r"""Parameters for fixing vulnerabilities."""
    session_id: NotRequired[str]
    r"""Parameter for grouping multiple interactions that belong to
    the same CodeMender session.
    """
    session_config: NotRequired[SessionConfigParam]
    r"""Optional session-specific configurations to override default agent
    behavior.
    """
    model: NotRequired[str]
    r"""The name of the model to use for the CodeMender agent. One
    CodeMender session will only use one model.
    """


class CodeMenderAgentConfig(BaseModel):
    r"""Configuration for the CodeMender agent."""

    type: Annotated[
        Annotated[
            Literal["code-mender"], AfterValidator(validate_const("code-mender"))
        ],
        pydantic.Field(alias="type"),
    ] = "code-mender"

    find_request: Optional[FindRequest] = None
    r"""Parameters for finding vulnerabilities."""

    fix_request: Optional[FixRequest] = None
    r"""Parameters for fixing vulnerabilities."""

    session_id: Optional[str] = None
    r"""Parameter for grouping multiple interactions that belong to
    the same CodeMender session.
    """

    session_config: Optional[SessionConfig] = None
    r"""Optional session-specific configurations to override default agent
    behavior.
    """

    model: Optional[str] = None
    r"""The name of the model to use for the CodeMender agent. One
    CodeMender session will only use one model.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["find_request", "fix_request", "session_id", "session_config", "model"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CodeMenderAgentConfig.model_rebuild()
except NameError:
    pass
