# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .allowlist import Allowlist, AllowlistParam
from typing import Literal, Union
from typing_extensions import TypeAliasType


Disabled = Literal["disabled",]
r"""Turns all network off."""


EnvironmentNetworkEgressAllowlistParam = TypeAliasType(
    "EnvironmentNetworkEgressAllowlistParam", Union[AllowlistParam, Disabled]
)
r"""Outbound networking configuration for the sandbox. Accepts an object with an 'allowlist' array to restrict traffic, or the string 'disabled' to turn off all network access. Omit entirely to allow all outbound traffic with no header injection."""


EnvironmentNetworkEgressAllowlist = TypeAliasType(
    "EnvironmentNetworkEgressAllowlist", Union[Allowlist, Disabled]
)
r"""Outbound networking configuration for the sandbox. Accepts an object with an 'allowlist' array to restrict traffic, or the string 'disabled' to turn off all network access. Omit entirely to allow all outbound traffic with no header injection."""
