# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UnrecognizedStr
from typing import List, Literal, Union
from typing_extensions import TypedDict


Operator = Union[
    Literal[
        "equals",
        "in",
    ],
    UnrecognizedStr,
]


class FilterRuleTypedDict(TypedDict):
    r"""A single declarative filter rule for webhook payload evaluation."""

    field_path: str
    r"""Required. JSON path in the payload to evaluate (e.g., \"payload.action\").
    Uses dot notation for nested fields.
    """
    operator: Operator
    values: List[str]
    r"""Required. Values to match against. For EQUALS, only values[0] is used."""


class FilterRule(BaseModel):
    r"""A single declarative filter rule for webhook payload evaluation."""

    field_path: str
    r"""Required. JSON path in the payload to evaluate (e.g., \"payload.action\").
    Uses dot notation for nested fields.
    """

    operator: Operator

    values: List[str]
    r"""Required. Values to match against. For EQUALS, only values[0] is used."""
