# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from ...utils import validate_const
from .filecontent import FileContent, FileContentParam
from .sessionconfig import SessionConfig, SessionConfigParam
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FixRequestParam(TypedDict):
    r"""Request parameters specific to FIX sessions, used for generating and
    validating security patches.
    """

    request: Literal["fix_request"]
    source_files: NotRequired[List[FileContentParam]]
    r"""A list of source files providing context for the remediation. These files
    are typically the ones containing the identified vulnerability.
    """
    finding_id: NotRequired[str]
    r"""The identifier of the specific security finding to be remediated. This ID
    maps to a previously discovered vulnerability.
    """
    description: NotRequired[str]
    r"""Additional context or custom instructions provided by the user to guide
    the patch generation process.
    """
    session_id: NotRequired[str]
    r"""Parameter for grouping multiple interactions that belong to
    the same CodeMender session.
    """
    session_config: NotRequired[SessionConfigParam]
    r"""The configuration of CodeMender sessions."""
    model: NotRequired[str]
    r"""The name of the model to use for the CodeMender agent. One
    CodeMender session will only use one model.
    """


class FixRequest(BaseModel):
    r"""Request parameters specific to FIX sessions, used for generating and
    validating security patches.
    """

    request: Annotated[
        Annotated[
            Literal["fix_request"], AfterValidator(validate_const("fix_request"))
        ],
        pydantic.Field(alias="request"),
    ] = "fix_request"

    source_files: Optional[List[FileContent]] = None
    r"""A list of source files providing context for the remediation. These files
    are typically the ones containing the identified vulnerability.
    """

    finding_id: Optional[str] = None
    r"""The identifier of the specific security finding to be remediated. This ID
    maps to a previously discovered vulnerability.
    """

    description: Optional[str] = None
    r"""Additional context or custom instructions provided by the user to guide
    the patch generation process.
    """

    session_id: Optional[str] = None
    r"""Parameter for grouping multiple interactions that belong to
    the same CodeMender session.
    """

    session_config: Optional[SessionConfig] = None
    r"""The configuration of CodeMender sessions."""

    model: Optional[str] = None
    r"""The name of the model to use for the CodeMender agent. One
    CodeMender session will only use one model.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "source_files",
                "finding_id",
                "description",
                "session_id",
                "session_config",
                "model",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    FixRequest.model_rebuild()
except NameError:
    pass
