# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from ...utils.unions import parse_open_union
from .agentoption import AgentOption
from .audiocontent import AudioContent, AudioContentParam
from .content import Content, ContentParam
from .deepresearchagentconfig import (
    DeepResearchAgentConfig,
    DeepResearchAgentConfigParam,
)
from .dynamicagentconfig import DynamicAgentConfig, DynamicAgentConfigParam
from .environment import Environment, EnvironmentParam
from .generationconfig import GenerationConfig, GenerationConfigParam
from .imagecontent import ImageContent, ImageContentParam
from .interactionsinput import InteractionsInput, InteractionsInputParam
from .model import Model
from .responseformat import ResponseFormat, ResponseFormatParam
from .responsemodality import ResponseModality
from .servicetier import ServiceTier
from .step import Step, StepParam
from .tool import Tool, ToolParam
from .usage import Usage, UsageParam
from .videocontent import VideoContent, VideoContentParam
from .webhookconfig import WebhookConfig, WebhookConfigParam
from functools import partial
import pydantic
from pydantic import ConfigDict, model_serializer, model_validator
from pydantic.functional_validators import BeforeValidator
from typing import Any, List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


InteractionEnvironmentTypedDict = TypeAliasType(
    "InteractionEnvironmentTypedDict", Union[EnvironmentParam, str]
)
r"""The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID."""


InteractionEnvironment = TypeAliasType(
    "InteractionEnvironment", Union[Environment, str]
)
r"""The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID."""


InteractionStatus = Union[
    Literal[
        "in_progress",
        "requires_action",
        "completed",
        "failed",
        "cancelled",
        "incomplete",
    ],
    UnrecognizedStr,
]
r"""Required. Output only. The status of the interaction."""


InteractionAgentConfigTypedDict = TypeAliasType(
    "InteractionAgentConfigTypedDict",
    Union[DynamicAgentConfigParam, DeepResearchAgentConfigParam],
)
r"""Configuration parameters for the agent interaction."""


class UnknownInteractionAgentConfig(BaseModel):
    r"""A InteractionAgentConfig variant the SDK doesn't recognize. Preserves the raw payload."""

    type: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)


_INTERACTION_AGENT_CONFIG_VARIANTS: dict[str, Any] = {
    "dynamic": DynamicAgentConfig,
    "deep-research": DeepResearchAgentConfig,
}


InteractionAgentConfig = Annotated[
    Union[DynamicAgentConfig, DeepResearchAgentConfig, UnknownInteractionAgentConfig],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="type",
            variants=_INTERACTION_AGENT_CONFIG_VARIANTS,
            unknown_cls=UnknownInteractionAgentConfig,
            union_name="InteractionAgentConfig",
        )
    ),
]
r"""Configuration parameters for the agent interaction."""


InteractionResponseFormatTypedDict = TypeAliasType(
    "InteractionResponseFormatTypedDict",
    Union[List[ResponseFormatParam], ResponseFormatParam],
)
r"""Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field."""


InteractionResponseFormat = TypeAliasType(
    "InteractionResponseFormat", Union[List[ResponseFormat], ResponseFormat]
)
r"""Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field."""


_LEGACY_LYRIA_MODELS = frozenset({"lyria-3-pro-preview", "lyria-3-clip-preview"})


class InteractionTypedDict(TypedDict):
    r"""The Interaction resource."""

    status: InteractionStatus
    r"""Required. Output only. The status of the interaction."""
    model: NotRequired[Model]
    r"""The model that will complete your prompt.\n\nSee [models](https://ai.google.dev/gemini-api/docs/models) for additional details."""
    agent: NotRequired[AgentOption]
    r"""The agent to interact with."""
    created: NotRequired[str]
    r"""Output only. The time at which the response was created in ISO 8601 format
    (YYYY-MM-DDThh:mm:ssZ).
    """
    environment: NotRequired[InteractionEnvironmentTypedDict]
    r"""The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID."""
    environment_id: NotRequired[str]
    r"""Output only. The environment ID for the interaction. Only populated if environment
    config is set in the request.
    """
    id: NotRequired[str]
    r"""Required. Output only. A unique identifier for the interaction completion."""
    previous_interaction_id: NotRequired[str]
    r"""The ID of the previous interaction, if any."""
    response_mime_type: NotRequired[str]
    r"""The mime type of the response. This is required if response_format is set."""
    response_modalities: NotRequired[List[ResponseModality]]
    r"""The requested modalities of the response (TEXT, IMAGE, AUDIO)."""
    role: NotRequired[str]
    r"""Output only. The role of the interaction."""
    service_tier: NotRequired[ServiceTier]
    steps: NotRequired[List[StepParam]]
    r"""Output only. The steps that make up the interaction, when included in the response."""
    system_instruction: NotRequired[str]
    r"""System instruction for the interaction."""
    tools: NotRequired[List[ToolParam]]
    r"""A list of tool declarations the model may call during interaction."""
    updated: NotRequired[str]
    r"""Output only. The time at which the response was last updated in ISO 8601 format
    (YYYY-MM-DDThh:mm:ssZ).
    """
    usage: NotRequired[UsageParam]
    r"""Statistics on the interaction request's token usage."""
    webhook_config: NotRequired[WebhookConfigParam]
    r"""Message for configuring webhook events for a request."""
    generation_config: NotRequired[GenerationConfigParam]
    r"""Configuration parameters for model interactions."""
    agent_config: NotRequired[InteractionAgentConfigTypedDict]
    r"""Configuration parameters for the agent interaction."""
    response_format: NotRequired[InteractionResponseFormatTypedDict]
    r"""Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field."""
    input: NotRequired[InteractionsInputParam]
    r"""The input for the interaction."""
    outputs: NotRequired[List[ContentParam]]
    r"""Output only. Legacy responses from the model."""
    output_text: NotRequired[str]
    r"""Concatenated text from the last model output in response to the current request.

    Note: this is added by the SDK.
    """
    output_image: NotRequired[ImageContentParam]
    r"""An image content block."""
    output_audio: NotRequired[AudioContentParam]
    r"""An audio content block."""
    output_video: NotRequired[VideoContentParam]
    r"""A video content block."""


class Interaction(BaseModel):
    r"""The Interaction resource."""

    status: InteractionStatus
    r"""Required. Output only. The status of the interaction."""

    model: Optional[Model] = None
    r"""The model that will complete your prompt.\n\nSee [models](https://ai.google.dev/gemini-api/docs/models) for additional details."""

    agent: Optional[AgentOption] = None
    r"""The agent to interact with."""

    created: Optional[str] = None
    r"""Output only. The time at which the response was created in ISO 8601 format
    (YYYY-MM-DDThh:mm:ssZ).
    """

    environment: Optional[InteractionEnvironment] = None
    r"""The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID."""

    environment_id: Optional[str] = None
    r"""Output only. The environment ID for the interaction. Only populated if environment
    config is set in the request.
    """

    id: Optional[str] = ""
    r"""Required. Output only. A unique identifier for the interaction completion."""

    previous_interaction_id: Optional[str] = None
    r"""The ID of the previous interaction, if any."""

    response_mime_type: Annotated[
        Optional[str],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
    ] = None
    r"""The mime type of the response. This is required if response_format is set."""

    response_modalities: Optional[List[ResponseModality]] = None
    r"""The requested modalities of the response (TEXT, IMAGE, AUDIO)."""

    role: Annotated[
        Optional[str],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
    ] = None
    r"""Output only. The role of the interaction."""

    service_tier: Optional[ServiceTier] = None

    steps: Optional[List[Step]] = None
    r"""Output only. The steps that make up the interaction, when included in the response."""

    system_instruction: Optional[str] = None
    r"""System instruction for the interaction."""

    tools: Optional[List[Tool]] = None
    r"""A list of tool declarations the model may call during interaction."""

    updated: Optional[str] = None
    r"""Output only. The time at which the response was last updated in ISO 8601 format
    (YYYY-MM-DDThh:mm:ssZ).
    """

    usage: Optional[Usage] = None
    r"""Statistics on the interaction request's token usage."""

    webhook_config: Optional[WebhookConfig] = None
    r"""Message for configuring webhook events for a request."""

    generation_config: Optional[GenerationConfig] = None
    r"""Configuration parameters for model interactions."""

    agent_config: Optional[InteractionAgentConfig] = None
    r"""Configuration parameters for the agent interaction."""

    response_format: Optional[InteractionResponseFormat] = None
    r"""Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field."""

    input: Optional[InteractionsInput] = None
    r"""The input for the interaction."""

    outputs: Annotated[
        Optional[List[Content]],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
    ] = None
    r"""Output only. Legacy responses from the model."""

    output_text: Optional[str] = None
    r"""Concatenated text from the last model output in response to the current request.

    Note: this is added by the SDK.
    """

    output_image: Optional[ImageContent] = None
    r"""An image content block."""

    output_audio: Optional[AudioContent] = None
    r"""An audio content block."""

    output_video: Optional[VideoContent] = None
    r"""A video content block."""

    @classmethod
    def _maybe_coerce_outputs(cls, data: Any) -> Any:
        if not isinstance(data, dict):
            return data
        if (
            not isinstance(data.get("model"), str)
            or data["model"] not in _LEGACY_LYRIA_MODELS
        ):
            return data
        if "steps" in data:
            return data
        if "outputs" not in data:
            return {**data, "steps": []}
        outputs = data["outputs"]
        if not isinstance(outputs, list):
            return {**data, "steps": []}

        coerced = {**data}
        coerced.pop("outputs")
        coerced["steps"] = [{"type": "model_output", "content": outputs}]
        return coerced

    @model_validator(mode="before")
    @classmethod
    def _coerce_outputs_to_steps(cls, data: Any) -> Any:
        return cls._maybe_coerce_outputs(data)

    @model_serializer(mode="wrap")
    def _serialize_model(self, handler):
        optional_fields = set(
            [
                "model",
                "agent",
                "created",
                "environment",
                "environment_id",
                "id",
                "previous_interaction_id",
                "response_mime_type",
                "response_modalities",
                "role",
                "service_tier",
                "steps",
                "system_instruction",
                "tools",
                "updated",
                "usage",
                "webhook_config",
                "generation_config",
                "agent_config",
                "response_format",
                "input",
                "outputs",
                "output_text",
                "output_image",
                "output_audio",
                "output_video",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
