# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


InteractionMetadataStatus = Union[
    Literal[
        "in_progress",
        "requires_action",
        "completed",
        "failed",
        "cancelled",
        "incomplete",
        "budget_exceeded",
        "queued",
    ],
    UnrecognizedStr,
]
r"""Output only. The status of the interaction."""


class InteractionMetadataTypedDict(TypedDict):
    r"""Metadata for an interaction, used for listing interactions."""

    created: NotRequired[str]
    r"""Output only. The time at which the response was created in ISO 8601 format
    (YYYY-MM-DDThh:mm:ssZ).
    """
    id: NotRequired[str]
    r"""Output only. A unique identifier for the interaction completion."""
    status: NotRequired[InteractionMetadataStatus]
    r"""Output only. The status of the interaction."""
    updated: NotRequired[str]
    r"""Output only. The time at which the response was last updated in ISO 8601 format
    (YYYY-MM-DDThh:mm:ssZ).
    """


class InteractionMetadata(BaseModel):
    r"""Metadata for an interaction, used for listing interactions."""

    created: Optional[str] = None
    r"""Output only. The time at which the response was created in ISO 8601 format
    (YYYY-MM-DDThh:mm:ssZ).
    """

    id: Optional[str] = None
    r"""Output only. A unique identifier for the interaction completion."""

    status: Optional[InteractionMetadataStatus] = None
    r"""Output only. The status of the interaction."""

    updated: Optional[str] = None
    r"""Output only. The time at which the response was last updated in ISO 8601 format
    (YYYY-MM-DDThh:mm:ssZ).
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["created", "id", "status", "updated"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
