# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel
from ...utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class LocalEnvironmentConfigParam(TypedDict):
    r"""Configuration for an environment that lives on the client connection rather
    than in a server-managed sandbox.

    When set (via Interaction.local_environment), the agent's filesystem and
    shell are treated as living on the client: the agent's built-in environment
    operations (e.g. reading/listing/editing files and running commands) are
    suspended on the server and yielded back to the client to execute, with their
    results returned on a subsequent turn. This is mutually exclusive with a
    server-managed `EnvironmentConfig` (remote_environment), since the
    environment is either on the client or in a server sandbox, never both.

    This governs only the agent's built-in environment. Client-declared function
    tools are always executed on the client regardless of this field.
    """

    type: Literal["local"]


class LocalEnvironmentConfig(BaseModel):
    r"""Configuration for an environment that lives on the client connection rather
    than in a server-managed sandbox.

    When set (via Interaction.local_environment), the agent's filesystem and
    shell are treated as living on the client: the agent's built-in environment
    operations (e.g. reading/listing/editing files and running commands) are
    suspended on the server and yielded back to the client to execute, with their
    results returned on a subsequent turn. This is mutually exclusive with a
    server-managed `EnvironmentConfig` (remote_environment), since the
    environment is either on the client or in a server sandbox, never both.

    This governs only the agent's built-in environment. Client-declared function
    tools are always executed on the client regardless of this field.
    """

    type: Annotated[
        Annotated[Literal["local"], AfterValidator(validate_const("local"))],
        pydantic.Field(alias="type"),
    ] = "local"


try:
    LocalEnvironmentConfig.model_rebuild()
except NameError:
    pass
