# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel
from ...utils.unions import parse_open_union
from .audioresponseformat import AudioResponseFormat, AudioResponseFormatParam
from .imageresponseformat import ImageResponseFormat, ImageResponseFormatParam
from .textresponseformat import TextResponseFormat, TextResponseFormatParam
from .videoresponseformat import VideoResponseFormat, VideoResponseFormatParam
from functools import partial
from pydantic import ConfigDict
from pydantic.functional_validators import BeforeValidator
from typing import Any, Literal, Union
from typing_extensions import Annotated, TypeAliasType


ResponseFormatParam = TypeAliasType(
    "ResponseFormatParam",
    Union[
        TextResponseFormatParam,
        AudioResponseFormatParam,
        ImageResponseFormatParam,
        VideoResponseFormatParam,
    ],
)


class UnknownResponseFormat(BaseModel):
    r"""A ResponseFormat variant the SDK doesn't recognize. Preserves the raw payload."""

    type: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)


_RESPONSE_FORMAT_VARIANTS: dict[str, Any] = {
    "audio": AudioResponseFormat,
    "image": ImageResponseFormat,
    "text": TextResponseFormat,
    "video": VideoResponseFormat,
}


ResponseFormat = Annotated[
    Union[
        AudioResponseFormat,
        ImageResponseFormat,
        TextResponseFormat,
        VideoResponseFormat,
        UnknownResponseFormat,
    ],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="type",
            variants=_RESPONSE_FORMAT_VARIANTS,
            unknown_cls=UnknownResponseFormat,
            union_name="ResponseFormat",
            lenient=True,
        )
    ),
]
