# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


PipelineMode = Union[
    Literal[
        "scan",
        "verify",
    ],
    UnrecognizedStr,
]
r"""The pipeline mode of a CodeMender session. It can only be used for a
find session.
"""


class SessionConfigParam(TypedDict):
    r"""The configuration of CodeMender sessions."""

    pipeline_mode: NotRequired[PipelineMode]
    r"""The pipeline mode of a CodeMender session. It can only be used for a
    find session.
    """
    topology: NotRequired[str]
    r"""The cognitive architecture or \"thinking\" topology used by the agent
    (e.g. \"default\", \"deep\").
    """
    max_rounds: NotRequired[int]
    r"""The maximum number of interaction rounds the agent is allowed to perform
    before reaching a timeout.
    """


class SessionConfig(BaseModel):
    r"""The configuration of CodeMender sessions."""

    pipeline_mode: Optional[PipelineMode] = None
    r"""The pipeline mode of a CodeMender session. It can only be used for a
    find session.
    """

    topology: Optional[str] = None
    r"""The cognitive architecture or \"thinking\" topology used by the agent
    (e.g. \"default\", \"deep\").
    """

    max_rounds: Optional[int] = None
    r"""The maximum number of interaction rounds the agent is allowed to perform
    before reaching a timeout.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["pipeline_mode", "topology", "max_rounds"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
