# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from ...utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Any, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


Execution = Union[
    Literal[
        "server",
        "client",
    ],
    UnrecognizedStr,
]
r"""The execution mode of the tool search."""


class ToolSearchParam(TypedDict):
    r"""A tool that allows the model to dynamically search for and load tools into
    the model’s context on demand. This allows clients to avoid loading all tool
    definitions up front and may help reduce overall token usage and cost.
    """

    description: NotRequired[str]
    r"""A description of the function. To be set only for client-side execution."""
    execution: NotRequired[Execution]
    r"""The execution mode of the tool search."""
    name: NotRequired[str]
    r"""The name of the function. To be set only for client-side execution."""
    parameters: NotRequired[Any]
    r"""The JSON Schema for the function's parameters. To be set only for
    client-side execution.
    """
    type: Literal["tool_search"]


class ToolSearch(BaseModel):
    r"""A tool that allows the model to dynamically search for and load tools into
    the model’s context on demand. This allows clients to avoid loading all tool
    definitions up front and may help reduce overall token usage and cost.
    """

    description: Optional[str] = None
    r"""A description of the function. To be set only for client-side execution."""

    execution: Optional[Execution] = None
    r"""The execution mode of the tool search."""

    name: Optional[str] = None
    r"""The name of the function. To be set only for client-side execution."""

    parameters: Optional[Any] = None
    r"""The JSON Schema for the function's parameters. To be set only for
    client-side execution.
    """

    type: Annotated[
        Annotated[
            Literal["tool_search"], AfterValidator(validate_const("tool_search"))
        ],
        pydantic.Field(alias="type"),
    ] = "tool_search"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description", "execution", "name", "parameters"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ToolSearch.model_rebuild()
except NameError:
    pass
