# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .filterrule import FilterRule, FilterRuleTypedDict
from .. import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class WebhookTriggerConfigFilterTypedDict(TypedDict):
    r"""Optional declarative filter rules evaluated before waking the container."""

    rules: NotRequired[List[FilterRuleTypedDict]]


class WebhookTriggerConfigFilter(BaseModel):
    r"""Optional declarative filter rules evaluated before waking the container."""

    rules: Optional[List[FilterRule]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["rules"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class VerificationTypedDict(TypedDict):
    r"""Signature verification configuration."""

    credential_id: NotRequired[str]
    r"""Resource ID referencing a stored credential for signature verification.
    Format: \"credentials/{credential_id}\" 
    """
    custom_header_name: NotRequired[str]
    r"""Custom header name override for non-preset HMAC verification.
    Only used when preset is empty (custom verification).
    """
    preset: NotRequired[str]
    r"""Named verification preset. Currently supported: \"github\".
    When set, the preset configures the header name, algorithm, and
    deduplication logic automatically.
    """


class Verification(BaseModel):
    r"""Signature verification configuration."""

    credential_id: Optional[str] = None
    r"""Resource ID referencing a stored credential for signature verification.
    Format: \"credentials/{credential_id}\" 
    """

    custom_header_name: Optional[str] = None
    r"""Custom header name override for non-preset HMAC verification.
    Only used when preset is empty (custom verification).
    """

    preset: Optional[str] = None
    r"""Named verification preset. Currently supported: \"github\".
    When set, the preset configures the header name, algorithm, and
    deduplication logic automatically.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["credential_id", "custom_header_name", "preset"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class WebhookTriggerConfigTypedDict(TypedDict):
    r"""Webhook-specific trigger configuration."""

    endpoint_url: NotRequired[str]
    r"""Output only. Public endpoint URL for receiving webhook POST requests.
    Format:
    https://generativelanguage.googleapis.com/v1beta/agents/{agent_id}/triggers/{trigger_id}
    """
    filter_: NotRequired[WebhookTriggerConfigFilterTypedDict]
    r"""Optional declarative filter rules evaluated before waking the container."""
    verification: NotRequired[VerificationTypedDict]
    r"""Signature verification configuration."""


class WebhookTriggerConfig(BaseModel):
    r"""Webhook-specific trigger configuration."""

    endpoint_url: Optional[str] = None
    r"""Output only. Public endpoint URL for receiving webhook POST requests.
    Format:
    https://generativelanguage.googleapis.com/v1beta/agents/{agent_id}/triggers/{trigger_id}
    """

    filter_: Annotated[
        Optional[WebhookTriggerConfigFilter], pydantic.Field(alias="filter")
    ] = None
    r"""Optional declarative filter rules evaluated before waking the container."""

    verification: Optional[Verification] = None
    r"""Signature verification configuration."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["endpoint_url", "filter", "verification"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    WebhookTriggerConfig.model_rebuild()
except NameError:
    pass
