# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable
# pylint: skip-file

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import AsyncBaseSDK, BaseSDK
from .sdkconfiguration import SDKConfiguration
from .locations_agents import AsyncLocationsAgents, LocationsAgents
from typing import Optional


class Locations(BaseSDK):
    @property
    def with_raw_response(self):
        return LocationsWithRawResponse(self)

    @property
    def with_streaming_response(self):
        return LocationsWithStreamingResponse(self)

    agents: LocationsAgents

    def __init__(
        self, sdk_config: SDKConfiguration, parent_ref: Optional[object] = None
    ) -> None:
        BaseSDK.__init__(self, sdk_config, parent_ref=parent_ref)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self):
        self.agents = LocationsAgents(
            self.sdk_configuration, parent_ref=self.parent_ref
        )


class LocationsWithRawResponse:
    def __init__(self, sdk: Locations) -> None:
        self._sdk = sdk

    @property
    def agents(self):
        return self._sdk.agents.with_raw_response


class LocationsWithStreamingResponse:
    def __init__(self, sdk: Locations) -> None:
        self._sdk = sdk

    @property
    def agents(self):
        return self._sdk.agents.with_streaming_response


class AsyncLocations(AsyncBaseSDK):
    @property
    def with_raw_response(self):
        return AsyncLocationsWithRawResponse(self)

    @property
    def with_streaming_response(self):
        return AsyncLocationsWithStreamingResponse(self)

    agents: AsyncLocationsAgents

    def __init__(
        self, sdk_config: SDKConfiguration, parent_ref: Optional[object] = None
    ) -> None:
        AsyncBaseSDK.__init__(self, sdk_config, parent_ref=parent_ref)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self):
        self.agents = AsyncLocationsAgents(
            self.sdk_configuration, parent_ref=self.parent_ref
        )


class AsyncLocationsWithRawResponse:
    def __init__(self, sdk: AsyncLocations) -> None:
        self._sdk = sdk

    @property
    def agents(self):
        return self._sdk.agents.with_raw_response


class AsyncLocationsWithStreamingResponse:
    def __init__(self, sdk: AsyncLocations) -> None:
        self._sdk = sdk

    @property
    def agents(self):
        return self._sdk.agents.with_streaming_response
