# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable
# pylint: skip-file

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import AsyncBaseSDK, BaseSDK
from .sdkconfiguration import SDKConfiguration
from .locations import AsyncLocations, Locations
from typing import Optional


class Projects(BaseSDK):
    @property
    def with_raw_response(self):
        return ProjectsWithRawResponse(self)

    @property
    def with_streaming_response(self):
        return ProjectsWithStreamingResponse(self)

    locations: Locations

    def __init__(
        self, sdk_config: SDKConfiguration, parent_ref: Optional[object] = None
    ) -> None:
        BaseSDK.__init__(self, sdk_config, parent_ref=parent_ref)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self):
        self.locations = Locations(self.sdk_configuration, parent_ref=self.parent_ref)


class ProjectsWithRawResponse:
    def __init__(self, sdk: Projects) -> None:
        self._sdk = sdk

    @property
    def locations(self):
        return self._sdk.locations.with_raw_response


class ProjectsWithStreamingResponse:
    def __init__(self, sdk: Projects) -> None:
        self._sdk = sdk

    @property
    def locations(self):
        return self._sdk.locations.with_streaming_response


class AsyncProjects(AsyncBaseSDK):
    @property
    def with_raw_response(self):
        return AsyncProjectsWithRawResponse(self)

    @property
    def with_streaming_response(self):
        return AsyncProjectsWithStreamingResponse(self)

    locations: AsyncLocations

    def __init__(
        self, sdk_config: SDKConfiguration, parent_ref: Optional[object] = None
    ) -> None:
        AsyncBaseSDK.__init__(self, sdk_config, parent_ref=parent_ref)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self):
        self.locations = AsyncLocations(
            self.sdk_configuration, parent_ref=self.parent_ref
        )


class AsyncProjectsWithRawResponse:
    def __init__(self, sdk: AsyncProjects) -> None:
        self._sdk = sdk

    @property
    def locations(self):
        return self._sdk.locations.with_raw_response


class AsyncProjectsWithStreamingResponse:
    def __init__(self, sdk: AsyncProjects) -> None:
        self._sdk = sdk

    @property
    def locations(self):
        return self._sdk.locations.with_streaming_response
