import requests
import json
import os

url = "https://openrouter.ai/api/v1/chat/completions"
headers = {
  "Authorization": f"Bearer {os.environ.get('OPENROUTER_API_KEY')}",
  "Content-Type": "application/json"
}
payload = {
  "models": [
    "nvidia/llama-3.1-nemotron-ultra-253b-v1",
    "google/gemma-3n-e4b-it",
    "shisa-ai/shisa-v2-llama3.3-70b"
  ],
  "messages": [
    {
      "role": "system",
      "content": "Olá tudo bem?"
    },
    {
      "role": "user",
      "content": ""
    }
  ],
  "temperature": 1.2,
  "stream": True,
  "provider": {
    "allow_fallbacks": True,
    "data_collection": "allow",
    "order": [
      "AI21",
      "AionLabs",
      "Avian",
      "Atoma",
      "Anthropic",
      "Amazon Bedrock",
      "Alibaba",
      "AtlasCloud",
      "CrofAI",
      "Cohere",
      "Chutes",
      "Cerebras",
      "Azure",
      "BaseTen",
      "Cloudflare",
      "GMICloud",
      "Friendli",
      "Featherless",
      "Enfer",
      "DeepSeek",
      "DeepInfra",
      "Crusoe",
      "Fireworks",
      "Kluster",
      "Inflection",
      "Inception",
      "Hyperbolic",
      "Google AI Studio",
      "Groq",
      "InferenceNet",
      "Infermatic",
      "Minimax",
      "Mancer 2",
      "Liquid",
      "Lambda",
      "Meta",
      "Z.AI",
      "Venice",
      "Together",
      "Targon",
      "Ubicloud",
      "WandB",
      "xAI",
      "Switchpoint",
      "Stealth",
      "Phala",
      "Perplexity",
      "Parasail",
      "SambaNova",
      "OpenInference",
      "Novita",
      "Nineteen",
      "NextBit",
      "OpenAI",
      "Nebius",
      "NCompass",
      "Morph",
      "Moonshot AI",
      "Mistral"
    ],
    "only": [
      "AI21",
      "AionLabs",
      "Alibaba",
      "Amazon Bedrock",
      "Anthropic",
      "AtlasCloud",
      "Atoma",
      "Avian",
      "Azure",
      "BaseTen",
      "Cerebras",
      "Chutes",
      "Cloudflare",
      "Cohere",
      "CrofAI",
      "Crusoe",
      "DeepInfra",
      "DeepSeek",
      "Enfer",
      "Featherless",
      "Fireworks",
      "Friendli",
      "GMICloud",
      "Google",
      "Google AI Studio",
      "Groq",
      "Hyperbolic",
      "Inception",
      "InferenceNet",
      "Infermatic",
      "Inflection",
      "Kluster",
      "Lambda",
      "Liquid",
      "Mancer 2",
      "Meta",
      "Minimax",
      "Mistral",
      "Moonshot AI",
      "Morph",
      "NCompass",
      "Nebius",
      "NextBit",
      "Nineteen",
      "Novita",
      "OpenAI",
      "OpenInference",
      "Parasail",
      "Perplexity",
      "Phala",
      "SambaNova",
      "Stealth",
      "Switchpoint",
      "Targon",
      "Together",
      "Ubicloud",
      "Venice",
      "WandB",
      "xAI",
      "Z.AI"
    ]
  }
}

response = requests.post(url, headers=headers, json=payload)
print(response.json())
