# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .genaierror import GenAiError
from typing import Any, TYPE_CHECKING

from ..utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .cancelinteractionbyid import (
        CancelInteractionByIDClientError,
        CancelInteractionByIDClientErrorData,
        CancelInteractionByIDServerError,
        CancelInteractionByIDServerErrorData,
    )
    from .createagent import (
        CreateAgentClientError,
        CreateAgentClientErrorData,
        CreateAgentServerError,
        CreateAgentServerErrorData,
    )
    from .createenvironment import (
        CreateEnvironmentClientError,
        CreateEnvironmentClientErrorData,
        CreateEnvironmentServerError,
        CreateEnvironmentServerErrorData,
    )
    from .createinteraction import (
        CreateInteractionClientError,
        CreateInteractionClientErrorData,
        CreateInteractionServerError,
        CreateInteractionServerErrorData,
    )
    from .createtrigger import (
        CreateTriggerClientError,
        CreateTriggerClientErrorData,
        CreateTriggerServerError,
        CreateTriggerServerErrorData,
    )
    from .createwebhook import (
        CreateWebhookClientError,
        CreateWebhookClientErrorData,
        CreateWebhookServerError,
        CreateWebhookServerErrorData,
    )
    from .deleteagent import (
        DeleteAgentClientError,
        DeleteAgentClientErrorData,
        DeleteAgentServerError,
        DeleteAgentServerErrorData,
    )
    from .deleteenvironment import (
        DeleteEnvironmentClientError,
        DeleteEnvironmentClientErrorData,
        DeleteEnvironmentServerError,
        DeleteEnvironmentServerErrorData,
    )
    from .deleteinteraction import (
        DeleteInteractionClientError,
        DeleteInteractionClientErrorData,
        DeleteInteractionServerError,
        DeleteInteractionServerErrorData,
    )
    from .deletetrigger import (
        DeleteTriggerClientError,
        DeleteTriggerClientErrorData,
        DeleteTriggerServerError,
        DeleteTriggerServerErrorData,
    )
    from .deletewebhook import (
        DeleteWebhookClientError,
        DeleteWebhookClientErrorData,
        DeleteWebhookServerError,
        DeleteWebhookServerErrorData,
    )
    from .genaidefaulterror import GenAiDefaultError
    from .getagent import (
        GetAgentClientError,
        GetAgentClientErrorData,
        GetAgentServerError,
        GetAgentServerErrorData,
    )
    from .getenvironment import (
        GetEnvironmentClientError,
        GetEnvironmentClientErrorData,
        GetEnvironmentServerError,
        GetEnvironmentServerErrorData,
    )
    from .getinteractionbyid import (
        GetInteractionByIDClientError,
        GetInteractionByIDClientErrorData,
        GetInteractionByIDServerError,
        GetInteractionByIDServerErrorData,
    )
    from .gettrigger import (
        GetTriggerClientError,
        GetTriggerClientErrorData,
        GetTriggerServerError,
        GetTriggerServerErrorData,
    )
    from .getwebhook import (
        GetWebhookClientError,
        GetWebhookClientErrorData,
        GetWebhookServerError,
        GetWebhookServerErrorData,
    )
    from .listagents import (
        ListAgentsClientError,
        ListAgentsClientErrorData,
        ListAgentsServerError,
        ListAgentsServerErrorData,
    )
    from .listenvironments import (
        ListEnvironmentsClientError,
        ListEnvironmentsClientErrorData,
        ListEnvironmentsServerError,
        ListEnvironmentsServerErrorData,
    )
    from .listtriggerexecutions import (
        ListTriggerExecutionsClientError,
        ListTriggerExecutionsClientErrorData,
        ListTriggerExecutionsServerError,
        ListTriggerExecutionsServerErrorData,
    )
    from .listtriggers import (
        ListTriggersClientError,
        ListTriggersClientErrorData,
        ListTriggersServerError,
        ListTriggersServerErrorData,
    )
    from .listwebhooks import (
        ListWebhooksClientError,
        ListWebhooksClientErrorData,
        ListWebhooksServerError,
        ListWebhooksServerErrorData,
    )
    from .no_response_error import NoResponseError
    from .pingwebhook import (
        PingWebhookClientError,
        PingWebhookClientErrorData,
        PingWebhookServerError,
        PingWebhookServerErrorData,
    )
    from .responsevalidationerror import ResponseValidationError
    from .rotatesigningsecret import (
        RotateSigningSecretClientError,
        RotateSigningSecretClientErrorData,
        RotateSigningSecretServerError,
        RotateSigningSecretServerErrorData,
    )
    from .runtrigger import (
        RunTriggerClientError,
        RunTriggerClientErrorData,
        RunTriggerServerError,
        RunTriggerServerErrorData,
    )
    from .updatetrigger import (
        UpdateTriggerClientError,
        UpdateTriggerClientErrorData,
        UpdateTriggerServerError,
        UpdateTriggerServerErrorData,
    )
    from .updatewebhook import (
        UpdateWebhookClientError,
        UpdateWebhookClientErrorData,
        UpdateWebhookServerError,
        UpdateWebhookServerErrorData,
    )

__all__ = [
    "CancelInteractionByIDClientError",
    "CancelInteractionByIDClientErrorData",
    "CancelInteractionByIDServerError",
    "CancelInteractionByIDServerErrorData",
    "CreateAgentClientError",
    "CreateAgentClientErrorData",
    "CreateAgentServerError",
    "CreateAgentServerErrorData",
    "CreateEnvironmentClientError",
    "CreateEnvironmentClientErrorData",
    "CreateEnvironmentServerError",
    "CreateEnvironmentServerErrorData",
    "CreateInteractionClientError",
    "CreateInteractionClientErrorData",
    "CreateInteractionServerError",
    "CreateInteractionServerErrorData",
    "CreateTriggerClientError",
    "CreateTriggerClientErrorData",
    "CreateTriggerServerError",
    "CreateTriggerServerErrorData",
    "CreateWebhookClientError",
    "CreateWebhookClientErrorData",
    "CreateWebhookServerError",
    "CreateWebhookServerErrorData",
    "DeleteAgentClientError",
    "DeleteAgentClientErrorData",
    "DeleteAgentServerError",
    "DeleteAgentServerErrorData",
    "DeleteEnvironmentClientError",
    "DeleteEnvironmentClientErrorData",
    "DeleteEnvironmentServerError",
    "DeleteEnvironmentServerErrorData",
    "DeleteInteractionClientError",
    "DeleteInteractionClientErrorData",
    "DeleteInteractionServerError",
    "DeleteInteractionServerErrorData",
    "DeleteTriggerClientError",
    "DeleteTriggerClientErrorData",
    "DeleteTriggerServerError",
    "DeleteTriggerServerErrorData",
    "DeleteWebhookClientError",
    "DeleteWebhookClientErrorData",
    "DeleteWebhookServerError",
    "DeleteWebhookServerErrorData",
    "GenAiDefaultError",
    "GenAiError",
    "GetAgentClientError",
    "GetAgentClientErrorData",
    "GetAgentServerError",
    "GetAgentServerErrorData",
    "GetEnvironmentClientError",
    "GetEnvironmentClientErrorData",
    "GetEnvironmentServerError",
    "GetEnvironmentServerErrorData",
    "GetInteractionByIDClientError",
    "GetInteractionByIDClientErrorData",
    "GetInteractionByIDServerError",
    "GetInteractionByIDServerErrorData",
    "GetTriggerClientError",
    "GetTriggerClientErrorData",
    "GetTriggerServerError",
    "GetTriggerServerErrorData",
    "GetWebhookClientError",
    "GetWebhookClientErrorData",
    "GetWebhookServerError",
    "GetWebhookServerErrorData",
    "ListAgentsClientError",
    "ListAgentsClientErrorData",
    "ListAgentsServerError",
    "ListAgentsServerErrorData",
    "ListEnvironmentsClientError",
    "ListEnvironmentsClientErrorData",
    "ListEnvironmentsServerError",
    "ListEnvironmentsServerErrorData",
    "ListTriggerExecutionsClientError",
    "ListTriggerExecutionsClientErrorData",
    "ListTriggerExecutionsServerError",
    "ListTriggerExecutionsServerErrorData",
    "ListTriggersClientError",
    "ListTriggersClientErrorData",
    "ListTriggersServerError",
    "ListTriggersServerErrorData",
    "ListWebhooksClientError",
    "ListWebhooksClientErrorData",
    "ListWebhooksServerError",
    "ListWebhooksServerErrorData",
    "NoResponseError",
    "PingWebhookClientError",
    "PingWebhookClientErrorData",
    "PingWebhookServerError",
    "PingWebhookServerErrorData",
    "ResponseValidationError",
    "RotateSigningSecretClientError",
    "RotateSigningSecretClientErrorData",
    "RotateSigningSecretServerError",
    "RotateSigningSecretServerErrorData",
    "RunTriggerClientError",
    "RunTriggerClientErrorData",
    "RunTriggerServerError",
    "RunTriggerServerErrorData",
    "UpdateTriggerClientError",
    "UpdateTriggerClientErrorData",
    "UpdateTriggerServerError",
    "UpdateTriggerServerErrorData",
    "UpdateWebhookClientError",
    "UpdateWebhookClientErrorData",
    "UpdateWebhookServerError",
    "UpdateWebhookServerErrorData",
]

_dynamic_imports: dict[str, str] = {
    "CancelInteractionByIDClientError": ".cancelinteractionbyid",
    "CancelInteractionByIDClientErrorData": ".cancelinteractionbyid",
    "CancelInteractionByIDServerError": ".cancelinteractionbyid",
    "CancelInteractionByIDServerErrorData": ".cancelinteractionbyid",
    "CreateAgentClientError": ".createagent",
    "CreateAgentClientErrorData": ".createagent",
    "CreateAgentServerError": ".createagent",
    "CreateAgentServerErrorData": ".createagent",
    "CreateEnvironmentClientError": ".createenvironment",
    "CreateEnvironmentClientErrorData": ".createenvironment",
    "CreateEnvironmentServerError": ".createenvironment",
    "CreateEnvironmentServerErrorData": ".createenvironment",
    "CreateInteractionClientError": ".createinteraction",
    "CreateInteractionClientErrorData": ".createinteraction",
    "CreateInteractionServerError": ".createinteraction",
    "CreateInteractionServerErrorData": ".createinteraction",
    "CreateTriggerClientError": ".createtrigger",
    "CreateTriggerClientErrorData": ".createtrigger",
    "CreateTriggerServerError": ".createtrigger",
    "CreateTriggerServerErrorData": ".createtrigger",
    "CreateWebhookClientError": ".createwebhook",
    "CreateWebhookClientErrorData": ".createwebhook",
    "CreateWebhookServerError": ".createwebhook",
    "CreateWebhookServerErrorData": ".createwebhook",
    "DeleteAgentClientError": ".deleteagent",
    "DeleteAgentClientErrorData": ".deleteagent",
    "DeleteAgentServerError": ".deleteagent",
    "DeleteAgentServerErrorData": ".deleteagent",
    "DeleteEnvironmentClientError": ".deleteenvironment",
    "DeleteEnvironmentClientErrorData": ".deleteenvironment",
    "DeleteEnvironmentServerError": ".deleteenvironment",
    "DeleteEnvironmentServerErrorData": ".deleteenvironment",
    "DeleteInteractionClientError": ".deleteinteraction",
    "DeleteInteractionClientErrorData": ".deleteinteraction",
    "DeleteInteractionServerError": ".deleteinteraction",
    "DeleteInteractionServerErrorData": ".deleteinteraction",
    "DeleteTriggerClientError": ".deletetrigger",
    "DeleteTriggerClientErrorData": ".deletetrigger",
    "DeleteTriggerServerError": ".deletetrigger",
    "DeleteTriggerServerErrorData": ".deletetrigger",
    "DeleteWebhookClientError": ".deletewebhook",
    "DeleteWebhookClientErrorData": ".deletewebhook",
    "DeleteWebhookServerError": ".deletewebhook",
    "DeleteWebhookServerErrorData": ".deletewebhook",
    "GenAiDefaultError": ".genaidefaulterror",
    "GetAgentClientError": ".getagent",
    "GetAgentClientErrorData": ".getagent",
    "GetAgentServerError": ".getagent",
    "GetAgentServerErrorData": ".getagent",
    "GetEnvironmentClientError": ".getenvironment",
    "GetEnvironmentClientErrorData": ".getenvironment",
    "GetEnvironmentServerError": ".getenvironment",
    "GetEnvironmentServerErrorData": ".getenvironment",
    "GetInteractionByIDClientError": ".getinteractionbyid",
    "GetInteractionByIDClientErrorData": ".getinteractionbyid",
    "GetInteractionByIDServerError": ".getinteractionbyid",
    "GetInteractionByIDServerErrorData": ".getinteractionbyid",
    "GetTriggerClientError": ".gettrigger",
    "GetTriggerClientErrorData": ".gettrigger",
    "GetTriggerServerError": ".gettrigger",
    "GetTriggerServerErrorData": ".gettrigger",
    "GetWebhookClientError": ".getwebhook",
    "GetWebhookClientErrorData": ".getwebhook",
    "GetWebhookServerError": ".getwebhook",
    "GetWebhookServerErrorData": ".getwebhook",
    "ListAgentsClientError": ".listagents",
    "ListAgentsClientErrorData": ".listagents",
    "ListAgentsServerError": ".listagents",
    "ListAgentsServerErrorData": ".listagents",
    "ListEnvironmentsClientError": ".listenvironments",
    "ListEnvironmentsClientErrorData": ".listenvironments",
    "ListEnvironmentsServerError": ".listenvironments",
    "ListEnvironmentsServerErrorData": ".listenvironments",
    "ListTriggerExecutionsClientError": ".listtriggerexecutions",
    "ListTriggerExecutionsClientErrorData": ".listtriggerexecutions",
    "ListTriggerExecutionsServerError": ".listtriggerexecutions",
    "ListTriggerExecutionsServerErrorData": ".listtriggerexecutions",
    "ListTriggersClientError": ".listtriggers",
    "ListTriggersClientErrorData": ".listtriggers",
    "ListTriggersServerError": ".listtriggers",
    "ListTriggersServerErrorData": ".listtriggers",
    "ListWebhooksClientError": ".listwebhooks",
    "ListWebhooksClientErrorData": ".listwebhooks",
    "ListWebhooksServerError": ".listwebhooks",
    "ListWebhooksServerErrorData": ".listwebhooks",
    "NoResponseError": ".no_response_error",
    "PingWebhookClientError": ".pingwebhook",
    "PingWebhookClientErrorData": ".pingwebhook",
    "PingWebhookServerError": ".pingwebhook",
    "PingWebhookServerErrorData": ".pingwebhook",
    "ResponseValidationError": ".responsevalidationerror",
    "RotateSigningSecretClientError": ".rotatesigningsecret",
    "RotateSigningSecretClientErrorData": ".rotatesigningsecret",
    "RotateSigningSecretServerError": ".rotatesigningsecret",
    "RotateSigningSecretServerErrorData": ".rotatesigningsecret",
    "RunTriggerClientError": ".runtrigger",
    "RunTriggerClientErrorData": ".runtrigger",
    "RunTriggerServerError": ".runtrigger",
    "RunTriggerServerErrorData": ".runtrigger",
    "UpdateTriggerClientError": ".updatetrigger",
    "UpdateTriggerClientErrorData": ".updatetrigger",
    "UpdateTriggerServerError": ".updatetrigger",
    "UpdateTriggerServerErrorData": ".updatetrigger",
    "UpdateWebhookClientError": ".updatewebhook",
    "UpdateWebhookClientErrorData": ".updatewebhook",
    "UpdateWebhookServerError": ".updatewebhook",
    "UpdateWebhookServerErrorData": ".updatewebhook",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
