# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from ..interactions import (
    deepresearchagentconfig as interactions_deepresearchagentconfig,
    dynamicagentconfig as interactions_dynamicagentconfig,
    generationconfig as interactions_generationconfig,
    interactionsinput as interactions_interactionsinput,
    model as interactions_model,
    responsemodality as interactions_responsemodality,
    servicetier as interactions_servicetier,
    tool as interactions_tool,
    webhookconfig as interactions_webhookconfig,
)
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class TriggerInteractionRequestParam(TypedDict):
    r"""Configuration parameters for the interaction request template."""

    stream: NotRequired[bool]
    r"""Input only. Whether the interaction will be streamed."""
    store: NotRequired[bool]
    r"""Input only. Whether to store the response and request for later retrieval."""
    background: NotRequired[bool]
    r"""Input only. Whether to run the model interaction in the background."""
    input: NotRequired[interactions_interactionsinput.InteractionsInputParam]
    r"""The input for the interaction."""
    agent: NotRequired[str]
    r"""The agent to execute."""
    model: NotRequired[interactions_model.Model]
    r"""The model that will complete your prompt.\n\nSee [models](https://ai.google.dev/gemini-api/docs/models) for additional details."""
    dynamic_config: NotRequired[interactions_dynamicagentconfig.DynamicAgentConfigParam]
    r"""Configuration for dynamic agents."""
    deep_research_config: NotRequired[
        interactions_deepresearchagentconfig.DeepResearchAgentConfigParam
    ]
    r"""Configuration for the Deep Research agent."""
    labels: NotRequired[Dict[str, str]]
    r"""Labels for the interaction."""
    tools: NotRequired[List[interactions_tool.ToolParam]]
    r"""A list of tool declarations the model may call during interaction."""
    system_instruction: NotRequired[str]
    r"""System instruction for the interaction."""
    generation_config: NotRequired[interactions_generationconfig.GenerationConfigParam]
    r"""Configuration parameters for model interactions."""
    response_modalities: NotRequired[
        List[interactions_responsemodality.ResponseModality]
    ]
    r"""The requested modalities of the response."""
    response_mime_type: NotRequired[str]
    r"""The mime type of the response."""
    previous_interaction_id: NotRequired[str]
    r"""Optional. The ID of the previous interaction, if any."""
    service_tier: NotRequired[interactions_servicetier.ServiceTier]
    webhook_config: NotRequired[interactions_webhookconfig.WebhookConfigParam]
    r"""Message for configuring webhook events for a request."""


class TriggerInteractionRequest(BaseModel):
    r"""Configuration parameters for the interaction request template."""

    stream: Optional[bool] = None
    r"""Input only. Whether the interaction will be streamed."""

    store: Optional[bool] = None
    r"""Input only. Whether to store the response and request for later retrieval."""

    background: Optional[bool] = None
    r"""Input only. Whether to run the model interaction in the background."""

    input: Optional[interactions_interactionsinput.InteractionsInput] = None
    r"""The input for the interaction."""

    agent: Optional[str] = None
    r"""The agent to execute."""

    model: Optional[interactions_model.Model] = None
    r"""The model that will complete your prompt.\n\nSee [models](https://ai.google.dev/gemini-api/docs/models) for additional details."""

    dynamic_config: Optional[interactions_dynamicagentconfig.DynamicAgentConfig] = None
    r"""Configuration for dynamic agents."""

    deep_research_config: Optional[
        interactions_deepresearchagentconfig.DeepResearchAgentConfig
    ] = None
    r"""Configuration for the Deep Research agent."""

    labels: Optional[Dict[str, str]] = None
    r"""Labels for the interaction."""

    tools: Optional[List[interactions_tool.Tool]] = None
    r"""A list of tool declarations the model may call during interaction."""

    system_instruction: Optional[str] = None
    r"""System instruction for the interaction."""

    generation_config: Optional[interactions_generationconfig.GenerationConfig] = None
    r"""Configuration parameters for model interactions."""

    response_modalities: Optional[
        List[interactions_responsemodality.ResponseModality]
    ] = None
    r"""The requested modalities of the response."""

    response_mime_type: Optional[str] = None
    r"""The mime type of the response."""

    previous_interaction_id: Optional[str] = None
    r"""Optional. The ID of the previous interaction, if any."""

    service_tier: Optional[interactions_servicetier.ServiceTier] = None

    webhook_config: Optional[interactions_webhookconfig.WebhookConfig] = None
    r"""Message for configuring webhook events for a request."""

    @model_serializer(mode="wrap")
    def _serialize_model(self, handler):
        optional_fields = set(
            [
                "stream",
                "store",
                "background",
                "input",
                "agent",
                "model",
                "dynamic_config",
                "deep_research_config",
                "labels",
                "tools",
                "system_instruction",
                "generation_config",
                "response_modalities",
                "response_mime_type",
                "previous_interaction_id",
                "service_tier",
                "webhook_config",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
