# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from ...utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .environment import (
        Environment,
        EnvironmentInput,
        EnvironmentInputParam,
        EnvironmentTypedDict,
        Network,
        NetworkEnum,
        NetworkParam,
        Status,
    )
    from .listenvironmentsresponse import (
        ListEnvironmentsResponse,
        ListEnvironmentsResponseTypedDict,
    )

__all__ = [
    "Environment",
    "EnvironmentInput",
    "EnvironmentInputParam",
    "EnvironmentTypedDict",
    "ListEnvironmentsResponse",
    "ListEnvironmentsResponseTypedDict",
    "Network",
    "NetworkEnum",
    "NetworkParam",
    "Status",
]

_dynamic_imports: dict[str, str] = {
    "Environment": ".environment",
    "EnvironmentInput": ".environment",
    "EnvironmentInputParam": ".environment",
    "EnvironmentTypedDict": ".environment",
    "Network": ".environment",
    "NetworkEnum": ".environment",
    "NetworkParam": ".environment",
    "Status": ".environment",
    "ListEnvironmentsResponse": ".listenvironmentsresponse",
    "ListEnvironmentsResponseTypedDict": ".listenvironmentsresponse",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
