# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from ...models.createinteraction import (
    CreateInteractionRequestParam as InteractionCreateParams,
)
from ...models.deleteinteraction import (
    DeleteInteractionRequestParam as InteractionDeleteParams,
)
from ...models.getinteractionbyid import (
    GetInteractionByIDRequestParam as InteractionGetParams,
)
from ...models.listagents import ListAgentsRequestParam as AgentListParams
from ...models.listwebhooks import ListWebhooksRequestParam as WebhookListParams
from ...types.agents.agent import Agent, AgentParam as AgentCreateParams
from ...types.agents.agentlistresponse import AgentListResponse
from ...types.interactions.agentoption import AgentOption
from ...types.interactions.allowedtools import AllowedTools
from ...types.interactions.allowlistentry import AllowlistEntry
from ...types.interactions.annotation import Annotation
from ...types.interactions.argumentsdelta import ArgumentsDelta
from ...types.interactions.audiocontent import AudioContent, AudioContentParam
from ...types.interactions.audiodelta import AudioDelta
from ...types.interactions.audioresponseformat import AudioResponseFormat
from ...types.interactions.codeexecution import CodeExecution
from ...types.interactions.codeexecutioncallarguments import CodeExecutionCallArguments
from ...types.interactions.codeexecutioncalldelta import CodeExecutionCallDelta
from ...types.interactions.codeexecutioncallstep import CodeExecutionCallStep
from ...types.interactions.codeexecutionresultdelta import CodeExecutionResultDelta
from ...types.interactions.codeexecutionresultstep import CodeExecutionResultStep
from ...types.interactions.computeruse import ComputerUse
from ...types.interactions.content import Content
from ...types.interactions.createagentinteraction import CreateAgentInteraction
from ...types.interactions.createmodelinteraction import CreateModelInteraction
from ...types.interactions.deepresearchagentconfig import DeepResearchAgentConfig
from ...types.interactions.documentcontent import DocumentContent
from ...types.interactions.documentdelta import DocumentDelta
from ...types.interactions.dynamicagentconfig import DynamicAgentConfig
from ...types.interactions.empty import Empty
from ...types.interactions.environment import Environment
from ...types.interactions.environmentnetworkegressallowlist_union import (
    EnvironmentNetworkEgressAllowlistUnion,
)
from ...types.interactions.error import Error
from ...types.interactions.errorevent import ErrorEvent, ErrorEventMetadata
from ...types.interactions.filecitation import FileCitation
from ...types.interactions.filesearch import FileSearch
from ...types.interactions.filesearchcalldelta import FileSearchCallDelta
from ...types.interactions.filesearchcallstep import FileSearchCallStep
from ...types.interactions.filesearchresult import FileSearchResult
from ...types.interactions.filesearchresultdelta import FileSearchResultDelta
from ...types.interactions.filesearchresultstep import FileSearchResultStep
from ...types.interactions.function import Function
from ...types.interactions.functioncallstep import FunctionCallStep
from ...types.interactions.functionresultdelta import FunctionResultDelta
from ...types.interactions.functionresultstep import FunctionResultStep
from ...types.interactions.generationconfig import GenerationConfig
from ...types.interactions.googlemaps import GoogleMaps
from ...types.interactions.googlemapscallarguments import GoogleMapsCallArguments
from ...types.interactions.googlemapscalldelta import GoogleMapsCallDelta
from ...types.interactions.googlemapscallstep import GoogleMapsCallStep
from ...types.interactions.googlemapsresult import GoogleMapsResult
from ...types.interactions.googlemapsresultdelta import GoogleMapsResultDelta
from ...types.interactions.googlemapsresultplaces import GoogleMapsResultPlaces
from ...types.interactions.googlemapsresultstep import GoogleMapsResultStep
from ...types.interactions.googlesearch import GoogleSearch
from ...types.interactions.googlesearchcallarguments import GoogleSearchCallArguments
from ...types.interactions.googlesearchcalldelta import GoogleSearchCallDelta
from ...types.interactions.googlesearchcallstep import GoogleSearchCallStep
from ...types.interactions.googlesearchresult import GoogleSearchResult
from ...types.interactions.googlesearchresultdelta import GoogleSearchResultDelta
from ...types.interactions.googlesearchresultstep import GoogleSearchResultStep
from ...types.interactions.groundingtoolcount import GroundingToolCount
from ...types.interactions.imageconfig import ImageConfig
from ...types.interactions.imagecontent import ImageContent
from ...types.interactions.imagedelta import ImageDelta
from ...types.interactions.imageresponseformat import ImageResponseFormat
from ...types.interactions.interaction import Interaction
from ...types.interactions.interactioncompletedevent import InteractionCompletedEvent
from ...types.interactions.interactioncreatedevent import InteractionCreatedEvent
from ...types.interactions.interactionsinput import InteractionsInput
from ...types.interactions.interactionsseevent import InteractionSSEEvent
from ...types.interactions.interactionsseeventinteraction import (
    InteractionSseEventInteraction,
)
from ...types.interactions.interactionssestreamevent import InteractionSSEStreamEvent
from ...types.interactions.interactionstatusupdate import (
    InteractionStatusUpdate,
    InteractionStatusUpdateMetadata,
)
from ...types.interactions.mcpserver import MCPServer
from ...types.interactions.mcpservertoolcalldelta import MCPServerToolCallDelta
from ...types.interactions.mcpservertoolcallstep import MCPServerToolCallStep
from ...types.interactions.mcpservertoolresultdelta import MCPServerToolResultDelta
from ...types.interactions.mcpservertoolresultstep import MCPServerToolResultStep
from ...types.interactions.mediaresolution import MediaResolution
from ...types.interactions.modalitytokens import ModalityTokens
from ...types.interactions.model import Model
from ...types.interactions.modeloutputstep import ModelOutputStep
from ...types.interactions.placecitation import PlaceCitation
from ...types.interactions.responseformat import ResponseFormat
from ...types.interactions.responsemodality import ResponseModality
from ...types.interactions.retrieval import Retrieval
from ...types.interactions.reviewsnippet import ReviewSnippet
from ...types.interactions.servicetier import ServiceTier
from ...types.interactions.source import Source
from ...types.interactions.speechconfig import SpeechConfig
from ...types.interactions.step import Step
from ...types.interactions.stepdelta import StepDelta
from ...types.interactions.stepdeltadata import StepDeltaData
from ...types.interactions.stepdeltametadata import StepDeltaMetadata
from ...types.interactions.stepstart import StepStart, StepStartMetadata
from ...types.interactions.stepstop import StepStop, StepStopMetadata
from ...types.interactions.textannotationdelta import TextAnnotationDelta
from ...types.interactions.textcontent import TextContent
from ...types.interactions.textdelta import TextDelta
from ...types.interactions.textresponseformat import TextResponseFormat
from ...types.interactions.thinkinglevel import ThinkingLevel
from ...types.interactions.thinkingsummaries import ThinkingSummaries
from ...types.interactions.thoughtsignaturedelta import ThoughtSignatureDelta
from ...types.interactions.thoughtstep import ThoughtStep
from ...types.interactions.thoughtsummarycontent import ThoughtSummaryContent
from ...types.interactions.thoughtsummarydelta import ThoughtSummaryDelta
from ...types.interactions.tool import Tool
from ...types.interactions.toolchoiceconfig import ToolChoiceConfig
from ...types.interactions.toolchoicetype import ToolChoiceType
from ...types.interactions.urlcitation import URLCitation
from ...types.interactions.urlcontext import URLContext
from ...types.interactions.urlcontextcallarguments import URLContextCallArguments
from ...types.interactions.urlcontextcalldelta import URLContextCallDelta
from ...types.interactions.urlcontextcallstep import Arguments, URLContextCallStep
from ...types.interactions.urlcontextresult import URLContextResult
from ...types.interactions.urlcontextresultdelta import URLContextResultDelta
from ...types.interactions.urlcontextresultstep import URLContextResultStep
from ...types.interactions.usage import Usage
from ...types.interactions.userinputstep import UserInputStep
from ...types.interactions.vertexaisearchconfig import VertexAISearchConfig
from ...types.interactions.videocontent import VideoContent, VideoContentParam
from ...types.interactions.videodelta import VideoDelta
from ...types.interactions.webhookconfig import WebhookConfig
from ...types.webhooks.pingwebhookrequest import (
    PingWebhookRequestParam as WebhookPingParams,
)
from ...types.webhooks.rotatesigningsecretrequest import (
    RotateSigningSecretRequestParam as WebhookRotateSigningSecretParams,
)
from ...types.webhooks.signingsecret import SigningSecret
from ...types.webhooks.webhook import Webhook, WebhookInputParam as WebhookCreateParams
from ...types.webhooks.webhooklistresponse import WebhookListResponse
from ...types.webhooks.webhookpingresponse import WebhookPingResponse
from ...types.webhooks.webhookrotatesigningsecretresponse import (
    WebhookRotateSigningSecretResponse,
)
from ...types.webhooks.webhookupdate import WebhookUpdateParam as WebhookUpdateParams

AgentDeleteResponse = Empty
ModelParam = Model
WebhookDeleteResponse = Empty
__all__ = [
    "Agent",
    "AgentCreateParams",
    "AgentDeleteResponse",
    "AgentListParams",
    "AgentListResponse",
    "AgentOption",
    "AllowedTools",
    "AllowlistEntry",
    "Annotation",
    "Arguments",
    "ArgumentsDelta",
    "AudioContent",
    "AudioContentParam",
    "AudioDelta",
    "AudioResponseFormat",
    "CodeExecution",
    "CodeExecutionCallArguments",
    "CodeExecutionCallDelta",
    "CodeExecutionCallStep",
    "CodeExecutionResultDelta",
    "CodeExecutionResultStep",
    "ComputerUse",
    "Content",
    "CreateAgentInteraction",
    "CreateModelInteraction",
    "DeepResearchAgentConfig",
    "DocumentContent",
    "DocumentDelta",
    "DynamicAgentConfig",
    "Empty",
    "Environment",
    "EnvironmentNetworkEgressAllowlistUnion",
    "Error",
    "ErrorEvent",
    "ErrorEventMetadata",
    "FileCitation",
    "FileSearch",
    "FileSearchCallDelta",
    "FileSearchCallStep",
    "FileSearchResult",
    "FileSearchResultDelta",
    "FileSearchResultStep",
    "Function",
    "FunctionCallStep",
    "FunctionResultDelta",
    "FunctionResultStep",
    "GenerationConfig",
    "GoogleMaps",
    "GoogleMapsCallArguments",
    "GoogleMapsCallDelta",
    "GoogleMapsCallStep",
    "GoogleMapsResult",
    "GoogleMapsResultDelta",
    "GoogleMapsResultPlaces",
    "GoogleMapsResultStep",
    "GoogleSearch",
    "GoogleSearchCallArguments",
    "GoogleSearchCallDelta",
    "GoogleSearchCallStep",
    "GoogleSearchResult",
    "GoogleSearchResultDelta",
    "GoogleSearchResultStep",
    "GroundingToolCount",
    "ImageConfig",
    "ImageContent",
    "ImageDelta",
    "ImageResponseFormat",
    "Interaction",
    "InteractionCompletedEvent",
    "InteractionCreateParams",
    "InteractionCreatedEvent",
    "InteractionDeleteParams",
    "InteractionGetParams",
    "InteractionSSEEvent",
    "InteractionSSEStreamEvent",
    "InteractionSseEventInteraction",
    "InteractionStatusUpdate",
    "InteractionStatusUpdateMetadata",
    "InteractionsInput",
    "MCPServer",
    "MCPServerToolCallDelta",
    "MCPServerToolCallStep",
    "MCPServerToolResultDelta",
    "MCPServerToolResultStep",
    "MediaResolution",
    "ModalityTokens",
    "Model",
    "ModelOutputStep",
    "ModelParam",
    "PlaceCitation",
    "ResponseFormat",
    "ResponseModality",
    "Retrieval",
    "ReviewSnippet",
    "ServiceTier",
    "SigningSecret",
    "Source",
    "SpeechConfig",
    "Step",
    "StepDelta",
    "StepDeltaData",
    "StepDeltaMetadata",
    "StepStart",
    "StepStartMetadata",
    "StepStop",
    "StepStopMetadata",
    "TextAnnotationDelta",
    "TextContent",
    "TextDelta",
    "TextResponseFormat",
    "ThinkingLevel",
    "ThinkingSummaries",
    "ThoughtSignatureDelta",
    "ThoughtStep",
    "ThoughtSummaryContent",
    "ThoughtSummaryDelta",
    "Tool",
    "ToolChoiceConfig",
    "ToolChoiceType",
    "URLCitation",
    "URLContext",
    "URLContextCallArguments",
    "URLContextCallDelta",
    "URLContextCallStep",
    "URLContextResult",
    "URLContextResultDelta",
    "URLContextResultStep",
    "Usage",
    "UserInputStep",
    "VertexAISearchConfig",
    "VideoContent",
    "VideoContentParam",
    "VideoDelta",
    "Webhook",
    "WebhookConfig",
    "WebhookCreateParams",
    "WebhookDeleteResponse",
    "WebhookListParams",
    "WebhookListResponse",
    "WebhookPingParams",
    "WebhookPingResponse",
    "WebhookRotateSigningSecretParams",
    "WebhookRotateSigningSecretResponse",
    "WebhookUpdateParams",
]
