# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable
# pylint: skip-file

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PromptedVoiceParam(TypedDict):
    r"""Parameters for prompted voice generation.
    Required in `CreateVoice` when `type` is `\"prompted\"`. Returned in
    `CreateVoice`, `GetVoice`, and `ListVoices` responses for prompted voices.
    """

    input: str
    r"""Required. The natural-language prompt describing the desired voice, e.g.
    \"A deep, booming male voice of a massive evil ogre in his middle years.\" 
    """
    base_voice: NotRequired[str]
    r"""Optional. The name or ID of an existing base voice to edit or remix.
    Use the voice name for prebuilt voices (e.g., `Puck`) or the voice ID for
    previously created voices (e.g., `voice_abc123`). This can be any
    prompted or replicated voice that the user has access to.
    When present, `input` describes relative alterations to make to the base
    voice.
    """


class PromptedVoice(BaseModel):
    r"""Parameters for prompted voice generation.
    Required in `CreateVoice` when `type` is `\"prompted\"`. Returned in
    `CreateVoice`, `GetVoice`, and `ListVoices` responses for prompted voices.
    """

    input: str
    r"""Required. The natural-language prompt describing the desired voice, e.g.
    \"A deep, booming male voice of a massive evil ogre in his middle years.\" 
    """

    base_voice: Optional[str] = None
    r"""Optional. The name or ID of an existing base voice to edit or remix.
    Use the voice name for prebuilt voices (e.g., `Puck`) or the voice ID for
    previously created voices (e.g., `voice_abc123`). This can be any
    prompted or replicated voice that the user has access to.
    When present, `input` describes relative alterations to make to the base
    voice.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["base_voice"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
